/**
 * Generate `components/packages/react/src/fluent-icons.tsx` from
 * `tooling/icons/manifest.json` and the vendored marks in `tooling/icons/svg/`.
 *
 * The system's icons are Microsoft's Fluent System Icons, filled weight. This
 * script is the equivalent of `tooling/brands/build.mjs` for the UI set: the
 * module is generated, never hand-authored.
 *
 *   node tooling/icons/build.mjs [--refresh] [--check]
 *
 * `--refresh` re-fetches every mark from the CDN and rewrites the vendored
 * copies. `--check` writes nothing and exits non-zero if the module is stale.
 *
 * ## Why the CDN is a SOURCE and not a runtime
 *
 * The obvious reading of "use the CDN" is an `<img src="https://cdn…">` per
 * icon, and it cannot work here. Every icon in this library is a lamp
 * ([[L15]]): it carries a control's state through `currentColor` and a
 * `drop-shadow` glow that traces its alpha. An `<img>` is an opaque document —
 * it inherits no colour, so hover, press and lit states all go dead — and a
 * network round trip per glyph means a server-rendered page paints its
 * controls empty and fills them in later.
 *
 * So the CDN is where the artwork COMES FROM, at build time, pinned to a
 * version. The fetched paths are vendored into this repository and compiled
 * into inline SVG components, which is what lets the glyph be `currentColor`
 * and lets a registry item stay one self-contained file. The vendored copy is
 * the fallback: with no network, the build still runs from what is committed.
 */

import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../..");
const SVG_DIR = resolve(import.meta.dirname, "svg");
const MANIFEST = resolve(import.meta.dirname, "manifest.json");
const TARGET = resolve(ROOT, "components/packages/react/src/fluent-icons.tsx");
const REFRESH = process.argv.includes("--refresh");
const CHECK = process.argv.includes("--check");

const manifest = JSON.parse(await readFile(MANIFEST, "utf8"));
const CDN = (name) =>
  `https://cdn.jsdelivr.net/npm/${manifest.source}@${manifest.version}/icons/${name}.svg`;
/* The five channel marks Fluent does not draw, because they are LOGOS. They
   come from the same place the brand set does, but colour-STRIPPED: these are
   the neutral forms a channel lamp lights through `currentColor`, not the
   brand's own colours. `td-brands` holds the colour-preserving pair. */
const LOGO_CDN = (slug) => `${manifest.logoSource}/${slug}/mono.svg`;

await mkdir(SVG_DIR, { recursive: true });
const vendored = new Set(await readdir(SVG_DIR).catch(() => []));

/**
 * One mark's raw SVG — from disk, or from the CDN when it is not vendored yet.
 *
 * Disk first even without `--refresh`: a build that silently depends on a
 * network it may not have is a build that fails in CI for a reason nobody can
 * see from the diff.
 */
async function markSource(name, url = CDN(name)) {
  const file = `${name}.svg`;
  if (!REFRESH && vendored.has(file)) return readFile(resolve(SVG_DIR, file), "utf8");
  const response = await fetch(url);
  if (!response.ok) {
    if (vendored.has(file)) return readFile(resolve(SVG_DIR, file), "utf8");
    throw new Error(`${name}: CDN returned ${response.status} and nothing is vendored to fall back to`);
  }
  const svg = await response.text();
  await writeFile(resolve(SVG_DIR, file), svg);
  return svg;
}

/** The viewBox and the path data, which is all a filled mark is. */
function extract(name, svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`${name}: no viewBox`);
  const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map(m => m[1]);
  if (!paths.length) throw new Error(`${name}: no path data — a mark here is a single-path fill`);
  /* Fluent ships some marks as several subpaths. Joined into one `d`, they
     fill as one shape, which is what the lamp needs: a glow traces the alpha
     of ONE element, and three sibling paths would each bloom separately. */
  return { viewBox, d: paths.join(" ") };
}

const roles = Object.entries(manifest.roles).sort(([a], [b]) => a.localeCompare(b));
const logos = Object.entries(manifest.logoRoles ?? {}).sort(([a], [b]) => a.localeCompare(b));
const marks = [];
for (const [role, name] of roles) {
  const { viewBox, d } = extract(name, await markSource(name));
  marks.push({ role, name, viewBox, d });
}
for (const [role, slug] of logos) {
  const file = `logo-${slug}`;
  const { viewBox, d } = extract(file, await markSource(file, LOGO_CDN(slug)));
  marks.push({ role, name: `${slug} (logo)`, viewBox, d });
}
marks.sort((a, b) => a.role.localeCompare(b.role));

const header = `// @generated by tooling/icons/build.mjs — do not edit.
"use client";

/**
 * The system's icon set: Microsoft Fluent System Icons, filled weight,
 * vendored from \`${manifest.source}@${manifest.version}\`.
 *
 * Filled is not a preference. An icon here is a lamp ([[L15]]) — it carries a
 * control's whole state through its colour and a \`drop-shadow\` glow, and a
 * glow traces the alpha edge of what it is applied to. An outline glyph glows
 * as a hollow outline, which reads as a smudge rather than a lit filament.
 *
 * Every mark is stripped to \`currentColor\` on the way in, so the lamp's ramp
 * can move it without the icon knowing anything about the ramp.
 *
 * Roles live in \`icons.ts\`; this module only draws. To change which mark a
 * role uses, edit \`tooling/icons/manifest.json\` and re-run the build.
 */

import type { SVGProps } from "react";

export interface FluentIconProps extends SVGProps<SVGSVGElement> {
  /** Edge length. \`1em\` so the glyph scales with the type it sits beside. */
  size?: number | string;
  /** The fill. \`currentColor\` so the lamp ramp can move it. */
  color?: string;
  /**
   * Swallowed, not forwarded. Fluent marks are filled by construction, so
   * there is nothing to switch — but call sites pass \`weight={LAMP_WEIGHT}\`
   * and \`weight\` is not an SVG attribute, so React would put it on the DOM.
   */
  weight?: string;
  /** Flip horizontally, for a mark that points. */
  mirrored?: boolean;
}

interface FluentGlyphProps extends FluentIconProps {
  viewBox: string;
  d: string;
}

function FluentGlyph({ viewBox, d, size = "1em", color = "currentColor", weight, mirrored, ...props }: FluentGlyphProps) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={viewBox}
      width={size}
      height={size}
      fill={color}
      transform={mirrored ? "scale(-1, 1)" : undefined}
      {...props}
    >
      <path d={d} />
    </svg>
  );
}
`;

const body = marks.map(({ role, name, viewBox, d }) =>
  `/** \`${name}\` */\nexport function ${role}(props: FluentIconProps) {\n  return <FluentGlyph viewBox="${viewBox}" d="${d}" {...props} />;\n}`,
).join("\n\n");

const generated = `${header}\n${body}\n`;
const current = await readFile(TARGET, "utf8").catch(() => null);

if (CHECK) {
  if (current !== generated) {
    console.error("fluent-icons.tsx is out of date. Run: pnpm icons:build");
    process.exit(1);
  }
  console.log(`Fluent icons up to date — ${marks.length} marks.`);
} else if (current === generated) {
  console.log(`Fluent icons up to date — ${marks.length} marks.`);
} else {
  await writeFile(TARGET, generated);
  console.log(`Generated ${marks.length} Fluent marks into fluent-icons.tsx`);
}
