import type { ReactElement, ReactNode } from "react";
import { Pressable, Text, TextInput, View, type PressableProps, type TextInputProps, type ViewProps } from "react-native";
import { useTonalDepthTheme } from "./theme";

export type TdNativeButtonVariant = "primary" | "secondary" | "destructive";
export interface TdNativeButtonProps extends PressableProps { label: string; variant?: TdNativeButtonVariant; loading?: boolean; className?: string }
export function TdNativeButton({ label, variant = "secondary", loading, disabled, className, style, ...props }: TdNativeButtonProps): ReactElement {
  const td=useTonalDepthTheme(); const fill=variant==="primary"?td.colors.brand:variant==="destructive"?td.colors.error:td.colors.surface; const color=variant==="secondary"?td.colors.ink:"#FFFFFF";
  return <Pressable {...props} {...({className} as object)} accessibilityRole="button" accessibilityState={{disabled:Boolean(disabled||loading),busy:Boolean(loading)}} disabled={disabled||loading} style={({pressed})=>[{minHeight:44,paddingHorizontal:16,borderRadius:td.radii["5"],backgroundColor:fill,alignItems:"center",justifyContent:"center",opacity:pressed?.8:1},typeof style==="function"?style({pressed}):style]}><Text style={{color,fontWeight:"600"}}>{loading?"Loading":label}</Text></Pressable>;
}
export function TdNativeBadge({ label, variant = "neutral", className }: { label:string; variant?:"neutral"|"brand"|"success"|"danger"; className?:string }) { const td=useTonalDepthTheme(); const color=variant==="brand"?td.colors.brand:variant==="success"?td.colors.green:variant==="danger"?td.colors.error:td.colors.ink2; return <View {...({className} as object)} accessible accessibilityLabel={label} style={{alignSelf:"flex-start",borderRadius:999,paddingHorizontal:9,paddingVertical:4,backgroundColor:`${color}24`}}><Text style={{color,fontWeight:"600"}}>{label}</Text></View>; }
export function TdNativeCard({ children, className, style, ...props }: ViewProps & { children:ReactNode; className?:string }) { const td=useTonalDepthTheme(); return <View {...props} {...({className} as object)} style={[{padding:16,borderRadius:td.radii["6"],backgroundColor:td.colors.surface,shadowColor:"#000",shadowOpacity:.14,shadowRadius:8,shadowOffset:{width:3,height:3},elevation:3},style]}>{children}</View>; }
export interface TdNativeInputProps extends TextInputProps { label:string; helperText?:string; error?:string; className?:string }
export function TdNativeInput({label,helperText,error,className,style,...props}:TdNativeInputProps):ReactElement{const td=useTonalDepthTheme();return <View><Text style={{color:td.colors.ink,fontWeight:"600",marginBottom:6}}>{label}</Text><TextInput {...props} {...({className} as object)} accessibilityLabel={label} accessibilityHint={error??helperText} accessibilityState={{disabled:props.editable===false}} style={[{minHeight:44,paddingHorizontal:12,borderRadius:td.radii["4"],backgroundColor:td.colors.surface,color:td.colors.ink,borderWidth:error?1:0,borderColor:td.colors.error},style]}/>{error||helperText?<Text accessibilityLiveRegion={error?"assertive":"polite"} style={{marginTop:4,color:error?td.colors.error:td.colors.ink2}}>{error??helperText}</Text>:null}</View>;}
