/* Generated by tooling/tokens/build_native.py. Do not edit. */
export const tonalDepthColors = {
  light: {
    "accent": "#00AAFF",
    "bg": "#F5F5F5",
    "brand": "#FF5E29",
    "error": "#FF4A45",
    "green": "#00C86A",
    "ink": "#1F1C17",
    "ink2": "#6E685E",
    "ink3": "#9A9388",
    "inkOnFill": "#1F1C17",
    "surface": "#F5F5F5",
    "surface2": "#E8E8E8",
  },
  dark: {
    "accent": "#00AAFF",
    "bg": "#1A1815",
    "brand": "#FF5E29",
    "error": "#FF4A45",
    "green": "#00C86A",
    "ink": "#F0EDE5",
    "ink2": "#9A9388",
    "ink3": "#6E685E",
    "inkOnFill": "#1F1C17",
    "surface": "#1A1815",
    "surface2": "#221F1A",
  },
} as const;
export const tonalDepthSpacing = {
  "1": 2.0,
  "2": 4.0,
  "3": 6.0,
  "4": 8.0,
  "5": 10.0,
  "6": 12.0,
  "7": 14.0,
  "8": 16.0,
  "9": 18.0,
  "10": 22.0,
  "11": 28.0,
  "12": 36.0,
  "13": 48.0
} as const;
export const tonalDepthRadii = {
  "1": 4.0,
  "2": 6.0,
  "3": 8.0,
  "4": 10.0,
  "5": 12.0,
  "6": 14.0,
  "7": 16.0,
  "8": 18.0,
  "9": 22.0,
  "10": 30.0
} as const;
export type TonalDepthThemeMode = keyof typeof tonalDepthColors;
