/**
 * Generate `components/packages/react/src/td-brands.tsx` from `tooling/brands/manifest.json`
 * and the vendored marks in `tooling/brands/svg/`.
 *
 * Brand logos are the sibling of the TD icon set: same "draw a mark here"
 * pattern, but colour-*preserving* rather than colour-neutral, because a brand
 * mark's identity is its colour. They are deliberately NOT part of `td-icons`
 * (which is filled + `currentColor` by invariant) and never route through
 * `icons.ts`. This script is the equivalent of `tooling/registry/generate.mjs`
 * for that family — the module is generated, not hand-authored.
 *
 *   node tooling/brands/build.mjs [--check]
 *
 * `--check` writes nothing and exits non-zero if the module is out of date.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "../..");
const SVG_DIR = resolve(import.meta.dirname, "svg");
const REFRESH = process.argv.includes("--refresh");

/**
 * Where a mark comes from when it is re-fetched.
 *
 * thesvg.org serves its catalogue from a public repository through jsDelivr,
 * which is what makes it usable as a build-time source: a pinned URL per slug,
 * no scraping, no API key. Same arrangement as the UI set in tooling/icons —
 * the CDN is where the artwork COMES FROM, and the vendored copy in `svg/` is
 * what the build actually reads, so a machine with no network still builds.
 *
 * `--refresh` is the only thing that goes to the network. A mark someone hands
 * us directly is dropped into `svg/` by hand and simply never re-fetched.
 */
/* `mono`, not `default`. The default export is full brand artwork — clip
   paths, gradients, several fills — and every mark in this manifest is `mode:
   mono`, a single path the component inks through `currentColor`. Fetching the
   colour version flattened the clipPath rect into the mark and drew Facebook
   and Instagram as solid black squares. */
const BRAND_CDN = (slug) => `https://cdn.jsdelivr.net/gh/glincker/thesvg@main/public/icons/${slug}/mono.svg`;

async function refreshMark(slug) {
  const response = await fetch(BRAND_CDN(slug));
  if (!response.ok) {
    console.warn(`  ${slug}: thesvg.org returned ${response.status} — keeping the vendored copy`);
    return;
  }
  await writeFile(resolve(SVG_DIR, `${slug}.svg`), await response.text());
  console.log(`  ${slug}: refreshed`);
}
const MANIFEST = resolve(import.meta.dirname, "manifest.json");
const TARGET = resolve(ROOT, "components/packages/react/src/td-brands.tsx");
const CHECK = process.argv.includes("--check");

/** The `viewBox` and inner markup of a vendored `<svg>`, `<title>` dropped. */
function parseSvg(svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error("vendored SVG has no viewBox");
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const inner = svg
    .slice(open + 1, svg.lastIndexOf("</svg>"))
    .replace(/<title>.*?<\/title>/gs, "")
    .trim();
  return { viewBox, inner };
}

/** Strip every hardcoded fill so the wrapper `<svg fill>` governs the ink. A
 *  mark flagged `preserveFills` keeps its own colours instead. */
function neutralise(inner, preserveFills) {
  return preserveFills ? inner : inner.replace(/\s*fill="[^"]*"/g, "");
}

const pascal = slug => slug.split(/[-_]/).map(part => part[0].toUpperCase() + part.slice(1)).join("");

function component(brand, inner) {
  const name = brand.component ?? `${pascal(brand.slug)}Logo`;
  const constName = brand.slug.replace(/[-_]/g, "_").toUpperCase();
  const brandProp = brand.color ? ` brand=${JSON.stringify(brand.color)}` : "";
  return {
    name,
    constName,
    const: `const ${constName} = ${JSON.stringify(inner)};`,
    fn: `/** ${brand.title}. */\nexport function ${name}(props: BrandLogoProps) {\n  return <BrandGlyph viewBox="${brand.viewBox}" inner={${constName}} title=${JSON.stringify(brand.title)}${brandProp} {...props} />;\n}`,
  };
}

const HEAD = `// GENERATED by tooling/brands/build.mjs — do not edit by hand.
// Add a mark in tooling/brands/svg + manifest.json, then run \`pnpm brands:build\`.
/**
 * Brand & company logos — the marks TonalDepth owns, drawn here.
 *
 * The sibling of \`td-icons\`: same idea, opposite colour rule. A UI icon is
 * colour-neutral so the lamp ramp can move it; a brand mark keeps its identity,
 * so these are colour-*preserving*. They never route through \`icons.ts\` and are
 * not held to the icon set's neutrality invariant.
 *
 * \`mono\` forces a mark to a single ink that follows \`currentColor\`; the
 * single-path marks below default to that. A mark with a resting brand colour
 * carries it through \`brand\`, and \`<BrandLogo name>\` resolves a mark by slug.
 */
import { type SVGProps } from "react";

export interface BrandLogoProps extends Omit<SVGProps<SVGSVGElement>, "color"> {
  /** Edge length. \`1em\` so the mark scales with the type beside it. */
  size?: number | string;
  /** Render in a single ink that follows \`currentColor\`. */
  mono?: boolean;
  /** Override the resting ink. Defaults to the mark's brand colour, else \`currentColor\`. */
  color?: string;
}

interface BrandGlyphProps extends BrandLogoProps {
  viewBox: string;
  inner: string;
  title: string;
  /** The mark's own resting colour, if it has one. */
  brand?: string;
}

function BrandGlyph({ viewBox, inner, title, brand, size = "1em", mono, color, ...props }: BrandGlyphProps) {
  const fill = mono ? "currentColor" : color ?? brand ?? "currentColor";
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox={viewBox}
      width={size}
      height={size}
      fill={fill}
      role="img"
      aria-label={title}
      dangerouslySetInnerHTML={{ __html: inner }}
      {...props}
    />
  );
}`;

async function build() {
  const manifest = JSON.parse(await readFile(MANIFEST, "utf8"));
  const marks = [];
  for (const brand of manifest.brands) {
    if (REFRESH) await refreshMark(brand.slug);
    const svg = await readFile(resolve(SVG_DIR, `${brand.slug}.svg`), "utf8");
    const { viewBox, inner } = parseSvg(svg);
    marks.push(component({ ...brand, viewBox }, neutralise(inner, brand.preserveFills)));
  }

  const slugs = manifest.brands.map(b => b.slug);

  const body = [
    HEAD,
    "// ── Marks ────────────────────────────────────────────────────────────────",
    marks.map(m => `${m.const}\n${m.fn}`).join("\n\n"),
    `export const BRAND_LOGOS = {\n${slugs.map((slug, i) => `  ${JSON.stringify(slug)}: ${marks[i].name},`).join("\n")}\n} as const;`,
    `export type BrandSlug = keyof typeof BRAND_LOGOS;`,
    `export const BRAND_SLUGS = [${slugs.map(s => JSON.stringify(s)).join(", ")}] as const satisfies readonly BrandSlug[];`,
    `/** Resolve a mark by slug. Returns \`null\` for an unknown name. */\nexport function BrandLogo({ name, ...props }: BrandLogoProps & { name: BrandSlug }) {\n  const Mark = BRAND_LOGOS[name];\n  return Mark ? <Mark {...props} /> : null;\n}`,
  ].join("\n\n") + "\n";

  return body;
}

const generated = await build();
const current = await readFile(TARGET, "utf8").catch(() => null);

if (current === generated) {
  console.log(`Brand logos up to date — ${JSON.parse(await readFile(MANIFEST, "utf8")).brands.length} marks.`);
} else if (CHECK) {
  console.error("td-brands.tsx is out of date. Run: pnpm brands:build");
  process.exit(1);
} else {
  await writeFile(TARGET, generated);
  console.log(`Wrote ${TARGET}`);
}
