#!/usr/bin/env python3
"""Generate deterministic React Native/NativeWind and Flutter token outputs."""
from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tokens/source/tokens.json"
TS_OUT = ROOT / "components/packages/nativewind/src/tokens.ts"
DART_OUT = ROOT / "components/packages/flutter/lib/src/generated/tonaldepth_tokens.dart"

PUBLIC_COLORS = ("accent", "bg", "brand", "error", "green", "ink", "ink-2", "ink-3", "ink-on-fill", "surface", "surface-2")

def dart_name(value: str) -> str:
    parts = re.split(r"[-.]", value)
    return parts[0] + "".join(part.title() for part in parts[1:])

def main() -> None:
    source = json.loads(SOURCE.read_text(encoding="utf-8"))
    indexed = {item["path"]: item for item in source["tokens"]}
    colors = {name: indexed[f"color.{name}"] for name in PUBLIC_COLORS}
    spacing = {str(i): indexed[f"spacing.{i}"]["$value"] for i in range(1, 14)}
    radii = {str(i): indexed[f"radius.{i}"]["$value"] for i in range(1, 11)}

    def mode(item: dict, name: str) -> str:
        value = item.get("$extensions", {}).get("tonaldepth", {}).get("modes", {}).get(name, item["$value"])
        return value if isinstance(value, str) and value.startswith("#") else item["$value"]

    ts = [
        "/* Generated by tooling/tokens/build_native.py. Do not edit. */",
        "export const tonalDepthColors = {",
        "  light: {",
        *[f'    {json.dumps(dart_name(name))}: {json.dumps(item["$value"])},' for name, item in colors.items()],
        "  },",
        "  dark: {",
        *[f'    {json.dumps(dart_name(name))}: {json.dumps(mode(item, "dark"))},' for name, item in colors.items()],
        "  },",
        "} as const;",
        f"export const tonalDepthSpacing = {json.dumps({k: float(v[:-2]) for k, v in spacing.items()}, indent=2)} as const;",
        f"export const tonalDepthRadii = {json.dumps({k: float(v[:-2]) for k, v in radii.items()}, indent=2)} as const;",
        "export type TonalDepthThemeMode = keyof typeof tonalDepthColors;",
        "",
    ]
    TS_OUT.parent.mkdir(parents=True, exist_ok=True)
    TS_OUT.write_text("\n".join(ts), encoding="utf-8")

    def color(value: str) -> str:
        return f"Color(0xFF{value[1:].upper()})"
    dart = [
        "// Generated by tooling/tokens/build_native.py. Do not edit.",
        "import 'package:flutter/material.dart';",
        "",
        "abstract final class TonalDepthGeneratedColors {",
        *[f"  static const {dart_name(name)}Light = {color(item['$value'])};" for name, item in colors.items()],
        *[f"  static const {dart_name(name)}Dark = {color(mode(item, 'dark'))};" for name, item in colors.items()],
        "}",
        "",
        "abstract final class TonalDepthGeneratedSpacing {",
        *[f"  static const s{key} = {float(value[:-2])};" for key, value in spacing.items()],
        "}",
        "",
        "abstract final class TonalDepthGeneratedRadii {",
        *[f"  static const r{key} = {float(value[:-2])};" for key, value in radii.items()],
        "}",
        "",
    ]
    DART_OUT.parent.mkdir(parents=True, exist_ok=True)
    DART_OUT.write_text("\n".join(dart), encoding="utf-8")
    print(f"Generated native tokens: {len(colors)} colors, {len(spacing)} spacing values, {len(radii)} radii")

if __name__ == "__main__":
    main()
